### ISSUE TITLE
No gulp file

### ISSUE THREAD

**Issue by goekhanak** [sandermak/typescript-presentation#1]
Great presentation however the gulp files for running the demos are missing.

**Comment by sandermak** [comment]
Thanks for checking it out! In the presentation, I used the TypeScript playground to show the examples in  `codesamples_livecode`, and I used IntelliJ (WebStorm)'s built-in TypeScript compilation to build the `demo_jquery` example. So, no Gulp files necessary.

**Comment by goekhanak** [comment]
i see may be you can update the instructions in _readme.md_ which refers to gulp.

**Comment by sandermak** [comment]
Ah, now I see, you're talking about the example in `demo_typescript-angular-requirejs`. And indeed, the gulpfile was missing there due to an overzealous gitignore. Fixed now. Thanks for reporting!
